---
sidebar: sidebar 
permalink: alerts-faq.html 
keywords: alerts faq, alerts frequently asked questions, bluexp, bluexp alert 
summary: このBlueXP  アラートFAQは、質問に対する簡単な回答を探している場合に役立ちます。 
---
= BlueXP  アラートに関するよくある質問
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
この FAQ は、質問に対する簡単な回答を探している場合に役立ちます。



== BlueXP  アラートへのアクセス

* BlueXP  アラートのURLは何ですか？*BlueXP  コンソールにアクセスするには、ブラウザで次のように入力します。 https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^]

* BlueXP  アラートを使用するにはライセンスが必要ですか？*

BlueXP  アラートサービスにはNetApp ONTAP 9 .10以上のライセンスが必要です。ライセンスをBlueXP  デジタルウォレットに入力する必要はありません。

このサービスの試用版ライセンスは必要ありません。

* BlueXP  アラートはどのようにして有効にしますか？*BlueXP  アラートを有効にする必要はありません。アラートオプションは、BlueXP  の左側のナビゲーションで自動的に有効になります。

BlueXP  Connectorを使用すると、サービスに適した機能が含まれます。

** BlueXP  アラートは、標準モード、制限モード、プライベートモードで使用できますか。**このサービスは、BlueXP  標準（パブリック）でのみ導入できます。

すべてのBlueXP  サービスにおけるこれらのモードの詳細については、を参照してください https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXPの導入モード"^]。

**アクセス権限はどのように処理されますか?**BlueXP  アラートサービスを開始してワークロードを検出できるのは、BlueXP  組織の管理者だけです（これにはリソースの使用をコミットする必要があるため）。

アラートは、ログインしているユーザに対して、そのBlueXP  組織内のクラスタのリソースへのアクセスに応じて表示されます。

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["BlueXP  組織の詳細"]です。



== アラートを表示します

**アラートの受信を開始するまで、どのくらい待機する必要がありますか?**

最初の検出まで最大15分、その後アラートが表示されるまで最大5分待ちます。これはアラートごとに異なります。

** BlueXP  コネクタなしで直接モードを使用している場合、ONTAPのアラートが表示されないのはなぜですか。*

BlueXP  アラートは、オンプレミスの標準BlueXP  Connectorを使用してのみ使用できます。直接モードを使用してもクラスタは監視されず、アラートも表示されません。

**一部のアラートが[アラート]リストページから消えてしまうのはなぜですか?**

アラート機能は、一部のアラートをアクティブ状態に保持し、カウンタの条件が満たされるか一定の期間に達した時点で閉じます。これはアラートごとに異なります。

すべてのアラートを表示するには、[Status]列フィルタを選択し、[Closed]オプションを選択します。



== 情報の表示

**どのデバイス解像度が最適ですか?**BlueXP  アラートに推奨されるデバイス解決策は1920 x 1080以上です。

**どのブラウザを使用すればよいですか?**最新のブラウザは機能します。
